/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZonesInterventionRouteImport } from './routes/zones-intervention'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ExperienceRouteImport } from './routes/experience'
import { Route as DeveloppeurLaravelFreelanceRouteImport } from './routes/developpeur-laravel-freelance'
import { Route as DeveloppeurAngularFreelanceRouteImport } from './routes/developpeur-angular-freelance'
import { Route as CreationSiteWebYvelinesRouteImport } from './routes/creation-site-web-yvelines'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CgvRouteImport } from './routes/cgv'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as ApplicationsWebSurMesureRouteImport } from './routes/applications-web-sur-mesure'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const ZonesInterventionRoute = ZonesInterventionRouteImport.update({
  id: '/zones-intervention',
  path: '/zones-intervention',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceRoute = ExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloppeurLaravelFreelanceRoute =
  DeveloppeurLaravelFreelanceRouteImport.update({
    id: '/developpeur-laravel-freelance',
    path: '/developpeur-laravel-freelance',
    getParentRoute: () => rootRouteImport,
  } as any)
const DeveloppeurAngularFreelanceRoute =
  DeveloppeurAngularFreelanceRouteImport.update({
    id: '/developpeur-angular-freelance',
    path: '/developpeur-angular-freelance',
    getParentRoute: () => rootRouteImport,
  } as any)
const CreationSiteWebYvelinesRoute = CreationSiteWebYvelinesRouteImport.update({
  id: '/creation-site-web-yvelines',
  path: '/creation-site-web-yvelines',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CgvRoute = CgvRouteImport.update({
  id: '/cgv',
  path: '/cgv',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsWebSurMesureRoute =
  ApplicationsWebSurMesureRouteImport.update({
    id: '/applications-web-sur-mesure',
    path: '/applications-web-sur-mesure',
    getParentRoute: () => rootRouteImport,
  } as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/applications-web-sur-mesure': typeof ApplicationsWebSurMesureRoute
  '/blog': typeof BlogRouteWithChildren
  '/cgv': typeof CgvRoute
  '/contact': typeof ContactRoute
  '/creation-site-web-yvelines': typeof CreationSiteWebYvelinesRoute
  '/developpeur-angular-freelance': typeof DeveloppeurAngularFreelanceRoute
  '/developpeur-laravel-freelance': typeof DeveloppeurLaravelFreelanceRoute
  '/experience': typeof ExperienceRoute
  '/faq': typeof FaqRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/projects': typeof ProjectsRoute
  '/services': typeof ServicesRoute
  '/zones-intervention': typeof ZonesInterventionRoute
  '/blog/$slug': typeof BlogSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/applications-web-sur-mesure': typeof ApplicationsWebSurMesureRoute
  '/blog': typeof BlogRouteWithChildren
  '/cgv': typeof CgvRoute
  '/contact': typeof ContactRoute
  '/creation-site-web-yvelines': typeof CreationSiteWebYvelinesRoute
  '/developpeur-angular-freelance': typeof DeveloppeurAngularFreelanceRoute
  '/developpeur-laravel-freelance': typeof DeveloppeurLaravelFreelanceRoute
  '/experience': typeof ExperienceRoute
  '/faq': typeof FaqRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/projects': typeof ProjectsRoute
  '/services': typeof ServicesRoute
  '/zones-intervention': typeof ZonesInterventionRoute
  '/blog/$slug': typeof BlogSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/applications-web-sur-mesure': typeof ApplicationsWebSurMesureRoute
  '/blog': typeof BlogRouteWithChildren
  '/cgv': typeof CgvRoute
  '/contact': typeof ContactRoute
  '/creation-site-web-yvelines': typeof CreationSiteWebYvelinesRoute
  '/developpeur-angular-freelance': typeof DeveloppeurAngularFreelanceRoute
  '/developpeur-laravel-freelance': typeof DeveloppeurLaravelFreelanceRoute
  '/experience': typeof ExperienceRoute
  '/faq': typeof FaqRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/projects': typeof ProjectsRoute
  '/services': typeof ServicesRoute
  '/zones-intervention': typeof ZonesInterventionRoute
  '/blog/$slug': typeof BlogSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/applications-web-sur-mesure'
    | '/blog'
    | '/cgv'
    | '/contact'
    | '/creation-site-web-yvelines'
    | '/developpeur-angular-freelance'
    | '/developpeur-laravel-freelance'
    | '/experience'
    | '/faq'
    | '/mentions-legales'
    | '/projects'
    | '/services'
    | '/zones-intervention'
    | '/blog/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/applications-web-sur-mesure'
    | '/blog'
    | '/cgv'
    | '/contact'
    | '/creation-site-web-yvelines'
    | '/developpeur-angular-freelance'
    | '/developpeur-laravel-freelance'
    | '/experience'
    | '/faq'
    | '/mentions-legales'
    | '/projects'
    | '/services'
    | '/zones-intervention'
    | '/blog/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/applications-web-sur-mesure'
    | '/blog'
    | '/cgv'
    | '/contact'
    | '/creation-site-web-yvelines'
    | '/developpeur-angular-freelance'
    | '/developpeur-laravel-freelance'
    | '/experience'
    | '/faq'
    | '/mentions-legales'
    | '/projects'
    | '/services'
    | '/zones-intervention'
    | '/blog/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ApplicationsWebSurMesureRoute: typeof ApplicationsWebSurMesureRoute
  BlogRoute: typeof BlogRouteWithChildren
  CgvRoute: typeof CgvRoute
  ContactRoute: typeof ContactRoute
  CreationSiteWebYvelinesRoute: typeof CreationSiteWebYvelinesRoute
  DeveloppeurAngularFreelanceRoute: typeof DeveloppeurAngularFreelanceRoute
  DeveloppeurLaravelFreelanceRoute: typeof DeveloppeurLaravelFreelanceRoute
  ExperienceRoute: typeof ExperienceRoute
  FaqRoute: typeof FaqRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  ProjectsRoute: typeof ProjectsRoute
  ServicesRoute: typeof ServicesRoute
  ZonesInterventionRoute: typeof ZonesInterventionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zones-intervention': {
      id: '/zones-intervention'
      path: '/zones-intervention'
      fullPath: '/zones-intervention'
      preLoaderRoute: typeof ZonesInterventionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience': {
      id: '/experience'
      path: '/experience'
      fullPath: '/experience'
      preLoaderRoute: typeof ExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developpeur-laravel-freelance': {
      id: '/developpeur-laravel-freelance'
      path: '/developpeur-laravel-freelance'
      fullPath: '/developpeur-laravel-freelance'
      preLoaderRoute: typeof DeveloppeurLaravelFreelanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developpeur-angular-freelance': {
      id: '/developpeur-angular-freelance'
      path: '/developpeur-angular-freelance'
      fullPath: '/developpeur-angular-freelance'
      preLoaderRoute: typeof DeveloppeurAngularFreelanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creation-site-web-yvelines': {
      id: '/creation-site-web-yvelines'
      path: '/creation-site-web-yvelines'
      fullPath: '/creation-site-web-yvelines'
      preLoaderRoute: typeof CreationSiteWebYvelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cgv': {
      id: '/cgv'
      path: '/cgv'
      fullPath: '/cgv'
      preLoaderRoute: typeof CgvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications-web-sur-mesure': {
      id: '/applications-web-sur-mesure'
      path: '/applications-web-sur-mesure'
      fullPath: '/applications-web-sur-mesure'
      preLoaderRoute: typeof ApplicationsWebSurMesureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ApplicationsWebSurMesureRoute: ApplicationsWebSurMesureRoute,
  BlogRoute: BlogRouteWithChildren,
  CgvRoute: CgvRoute,
  ContactRoute: ContactRoute,
  CreationSiteWebYvelinesRoute: CreationSiteWebYvelinesRoute,
  DeveloppeurAngularFreelanceRoute: DeveloppeurAngularFreelanceRoute,
  DeveloppeurLaravelFreelanceRoute: DeveloppeurLaravelFreelanceRoute,
  ExperienceRoute: ExperienceRoute,
  FaqRoute: FaqRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  ProjectsRoute: ProjectsRoute,
  ServicesRoute: ServicesRoute,
  ZonesInterventionRoute: ZonesInterventionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
